# Generated by Django 6.0.4 on 2026-09-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('project_leader', 'Project Leader'), ('project_manager', 'Project Manager'), ('team_member', 'Team Member')], default='team_member', max_length=20),
        ),
    ]
